import { Game, Category, SiteSettings, ContactMessage, MediaItem } from '../types';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Rummy', slug: 'rummy', icon: 'Spade', description: 'Popular cash rummy games with instant bank withdrawals.', gameCount: 4 },
  { id: 'cat-2', name: 'Teen Patti', slug: 'teen-patti', icon: 'Coins', description: 'Classic 3-card poker games with high daily sign up bonuses.', gameCount: 3 },
  { id: 'cat-3', name: 'Slots', slug: 'slots', icon: 'Dices', description: 'Vegas style slot machines with huge progressive jackpots.', gameCount: 2 },
  { id: 'cat-4', name: 'Aviator', slug: 'aviator', icon: 'Plane', description: 'High multiplier crash games with real-time payout tracking.', gameCount: 2 },
  { id: 'cat-5', name: 'Casino', slug: 'casino', icon: 'Crown', description: 'Live dealer roulette, blackjack, and baccarat tables.', gameCount: 2 },
  { id: 'cat-6', name: 'Fantasy Sports', slug: 'fantasy-sports', icon: 'Trophy', description: 'Cricket & football fantasy leagues with big mega contests.', gameCount: 2 },
  { id: 'cat-7', name: 'Arcade', slug: 'arcade', icon: 'Gamepad2', description: 'Ludo, Carrom, Snake, and quick casual skill gaming apps.', gameCount: 2 },
  { id: 'cat-8', name: 'Fishing', slug: 'fishing', icon: 'Fish', description: 'Ocean shooting & deep sea fish hunting games.', gameCount: 1 },
  { id: 'cat-9', name: 'Mines', slug: 'mines', icon: 'Bomb', description: 'Strategic grid minefield cash games with customizable risk.', gameCount: 1 },
  { id: 'cat-10', name: 'Poker', slug: 'poker', icon: 'Flame', description: 'Texas Holdem and Omaha high-stakes tournament tables.', gameCount: 1 },
  { id: 'cat-11', name: 'Color Prediction', slug: 'color-prediction', icon: 'Palette', description: 'Fast 1-minute color guess & win apps with instant payouts.', gameCount: 1 },
  { id: 'cat-12', name: 'Bingo', slug: 'bingo', icon: 'Sparkles', description: 'Fun multiplayer bingo rooms with daily free cards.', gameCount: 1 }
];

export const initialSettings: SiteSettings = {
  siteName: 'ALL JAIHO COMPANY',
  siteTagline: 'India\'s #1 Real Cash Gaming Directory & Verified APK Downloads',
  telegramLink: 'https://t.me/Soumy_6263',
  noticeTitle: 'IMPORTANT LEGAL NOTICE & RESPONSIBLE GAMING WARNING',
  noticeContent: 'Real money gaming involves financial risk and may be addictive. Play responsibly and at your own risk. This platform lists verified APKs for skill-based gaming applications. Online real money gaming is strictly restricted for users under 18 years of age and residents of Assam, Odisha, Telangana, Nagaland, Sikkim, and Andhra Pradesh.',
  restrictedStates: ['Assam', 'Odisha', 'Telangana', 'Nagaland', 'Sikkim', 'Andhra Pradesh'],
  maintenanceMode: false,
  contactEmail: 'support@alljaihocompany.com',
  contactPhone: '+91 98765 43210',
  whatsappLink: 'https://wa.me/919876543210',
  heroNotice: '⚡ 100% Verified APKs • Instant ₹51-₹500 Sign Up Bonuses • Fast Downloads',
  metaTitle: 'ALL JAIHO COMPANY - Download Real Cash Rummy, Teen Patti & Casino Games APK',
  metaDescription: 'Download 100% safe & verified gaming APKs. Best Real Cash Rummy, Teen Patti, Aviator, Slots, and Fantasy Sports apps with highest sign up bonuses & instant bank withdrawals.'
};

export const initialGames: Game[] = [
  {
    id: "game-1786264107359",
    ranking: 3,
    name: "WinRummy",
    slug: "winrummy",
    logo: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop&q=80",
    poster: "",
    banner: "",
    screenshots: [],
    shortDescription: "Verified mobile cash rummy application.",
    description: "Play WinRummy with thousands of real cash players daily. Instant withdrawal to bank and UPI.",
    category: "Rummy",
    bonus: 50,
    bonusLabel: "₹50 Cash Bonus",
    minWithdrawal: 100,
    rating: 4.8,
    version: "v1.0.0",
    apkSize: "35 MB",
    packageName: "com.jaiho.winrummy",
    developerName: "ALL JAIHO COMPANY",
    downloadCount: 1420,
    clickCount: 2310,
    lastUpdated: "2026-08-09",
    createdAt: "2026-08-09",
    updatedAt: "2026-08-09",
    downloadType: "OFFICIAL_WEBSITE",
    googlePlayUrl: "",
    officialWebsiteUrl: "https://www.winrummy15.com/?code=8JT3PRGQD2K&t=1785291319",
    directDownloadUrl: "https://www.winrummy15.com/?code=8JT3PRGQD2K&t=1785291319",
    downloadUrl: "https://www.winrummy15.com/?code=8JT3PRGQD2K&t=1785291319",
    externalStoreUrl: "",
    telegramGroup: "https://t.me/Soumy_6263",
    officialWebsite: "https://www.winrummy15.com/?code=8JT3PRGQD2K&t=1785291319",
    isFeatured: true,
    isTrending: false,
    isNew: true,
    status: "published",
    features: ["100% Verified APK", "High Speed Payouts", "Instant Bank Transfer"],
    withdrawalRules: ["Min withdrawal ₹100", "Instant bank/UPI processing"],
    registrationGuide: ["Install app and register with mobile number", "Enter OTP to claim ₹50 sign-up bonus"]
  },
  {
    id: "game-1786264055142",
    ranking: 2,
    name: "YONORAHUL",
    slug: "yonorahul",
    logo: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop&q=80",
    poster: "",
    banner: "",
    screenshots: [],
    shortDescription: "Popular multi-gaming app with Teen Patti, Rummy and Slots.",
    description: "YONORAHUL offers 20+ exciting skill gaming titles with daily free spins and fast withdrawals.",
    category: "Teen Patti",
    bonus: 51,
    bonusLabel: "₹51 Free Signup Bonus",
    minWithdrawal: 100,
    rating: 4.9,
    version: "v2.4.0",
    apkSize: "42 MB",
    packageName: "com.jaiho.yonorahul",
    developerName: "ALL JAIHO COMPANY",
    downloadCount: 3890,
    clickCount: 5400,
    lastUpdated: "2026-08-08",
    createdAt: "2026-08-08",
    updatedAt: "2026-08-08",
    downloadType: "DIRECT_DOWNLOAD",
    googlePlayUrl: "",
    officialWebsiteUrl: "https://www.yonorahul.com",
    directDownloadUrl: "https://www.yonorahul.com/download.apk",
    downloadUrl: "https://www.yonorahul.com/download.apk",
    externalStoreUrl: "",
    telegramGroup: "https://t.me/Soumy_6263",
    officialWebsite: "https://www.yonorahul.com",
    isFeatured: true,
    isTrending: true,
    isNew: false,
    status: "published",
    features: ["20+ Games Included", "24/7 Live Customer Care", "VIP Rewards Club"],
    withdrawalRules: ["Minimum withdrawal ₹100", "No TDS deduction on withdrawal"],
    registrationGuide: ["Download APK and install", "Sign up with mobile number & receive ₹51 bonus"]
  },
  {
    id: "game-1786264000100",
    ranking: 1,
    name: "JaiHo Rummy",
    slug: "jaiho-rummy",
    logo: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=200&h=200&fit=crop&q=80",
    poster: "",
    banner: "",
    screenshots: [],
    shortDescription: "Official JaiHo Rummy APK with maximum daily rewards.",
    description: "Play India's most trusted online Rummy app with over 10 Lakh registered players.",
    category: "Rummy",
    bonus: 100,
    bonusLabel: "₹100 Instant Bonus",
    minWithdrawal: 100,
    rating: 5.0,
    version: "v3.1.2",
    apkSize: "48 MB",
    packageName: "com.jaiho.rummy",
    developerName: "ALL JAIHO COMPANY",
    downloadCount: 8900,
    clickCount: 12400,
    lastUpdated: "2026-08-09",
    createdAt: "2026-08-01",
    updatedAt: "2026-08-09",
    downloadType: "DIRECT_DOWNLOAD",
    googlePlayUrl: "",
    officialWebsiteUrl: "https://t.me/Soumy_6263",
    directDownloadUrl: "https://t.me/Soumy_6263",
    downloadUrl: "https://t.me/Soumy_6263",
    externalStoreUrl: "",
    telegramGroup: "https://t.me/Soumy_6263",
    officialWebsite: "https://t.me/Soumy_6263",
    isFeatured: true,
    isTrending: true,
    isNew: false,
    status: "published",
    features: ["100% Safe & Anti-Cheat Verified", "Instant UPI Withdrawals", "Mega Daily Tournaments"],
    withdrawalRules: ["Min Withdrawal ₹100", "Unlimited daily withdrawals"],
    registrationGuide: ["Click Download APK", "Install & register with mobile number"]
  }
];

export const initialMediaItems: MediaItem[] = [
  {
    id: 'media-1',
    name: 'Rummy Circle Logo',
    url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&h=200&fit=crop&q=80',
    type: 'logo',
    size: '24 KB',
    uploadedAt: '2026-08-01'
  },
  {
    id: 'media-2',
    name: 'Teen Patti Banner',
    url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&h=400&fit=crop&q=80',
    type: 'banner',
    size: '120 KB',
    uploadedAt: '2026-08-03'
  }
];

export const initialContactMessages: ContactMessage[] = [
  {
    id: 'msg-1',
    name: 'Rohan Sharma',
    email: 'rohan@example.com',
    phone: '+91 9812345678',
    subject: 'APK Download Issue',
    message: 'Can you please add the latest version of Aviator Pro?',
    date: '2026-08-05 14:22',
    read: false
  }
];
